name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Flask
          pip install pytest

      - name: Run tests
        run: pytest

  deploy:
    runs-on: ubuntu-20.04
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remote SSH Command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/random_quotes_app
            pip install gunicorn
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install Flask
            pip install pytest
            chmod 600 ~/.ssh/id_rsa
            gunicorn --bind=${{ secrets.HOST }}:8000 random_quotes_app.main:app
            git pull origin main
            systemctl restart main
            systemctl status main

      # - name: Install Dependencies
      #   run: |
      #     pip install gunicorn
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     pip install Flask
      #     pip install pytest

      # - name: Run Gunicorn
      #   run: |
      #     chmod 600 ~/.ssh/id_rsa
      #     gunicorn --bind=${{ secrets.HOST }}:8000 random_quotes_app.main:app

      # - name: Deploy to Server
      #   run: |
      #     git pull origin main
      #     systemctl restart main
      #     systemctl status main

      - name: Debug
        run: |
          pwd
          ls -la
