name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    runs-on: ubuntu-20.04
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'

      - name: Remote SSH Command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |

            chmod 600 ~/.ssh/id_rsa

            git pull origin main
            systemctl restart main
            systemctl status main
